info:
  contact: {email: agitatesolidbee@gmail.com, name: ASB}
  description: 'Perform Google Maps tiles extent computations.'
  title: '21tiles'
  x-21-category: utilities
  x-21-github-project-url: https://github.com/savardiego/21tiles
  x-21-keywords: [maps, tile, extent, geo]
  x-21-usage: 'Send GET request to server with params in querystring. Request returns JSON object.'
  x-21-quick-buy: "21 buy 'http://10.244.65.224:5000/tile_coord?zoom=19&x=10.3526&y=46.8876' \n21 buy 'http://10.244.65.224:5000/tile_extent_geo?zoom=11&x=207&y=968' \n21 buy 'http://10.244.65.224:5000/tile_extent_merc?zoom=11&x=207&y=968'"
  x-21-total-price: {max: 5, min: 5}
basePath: /
paths:
      /tile_coord:
          get:
            summary: Returns tiles x and y.
            consumes: [application/x-www-form-urlencoded]
            produces: [application/json]
            parameters:
                - name: zoom
                  description: zoom level - from 0 to 21
                  in: query
                  required: true
                  schema:
                    type: integer
                - name: x
                  description: point longitude
                  in: query
                  required: true
                  schema:
                    type: number
                - name: y
                  description: point latitude
                  in: query
                  required: true
                  schema:
                    type: number
            responses:
              200:
                description: "Coordinates of the map tile that contains the point of given coordinates at the given zoom level. \nQuerystring: ?zoom=<zoom level>&x=<lon>&y=<lat>. \nAnswer:  { x: <tile x coord>, y: <tile y coord> }"
      /tile_extent_geo:
          get:
            summary: Returns geo extent of the tile at the given coords.
            consumes: [application/x-www-form-urlencoded]
            produces: [application/json]
            parameters:
                - name: zoom
                  description: zoom level - from 0 to 21
                  in: query
                  required: true
                  schema:
                    type: integer
                - name: x
                  description: tiles x coord
                  in: query
                  required: true
                  schema:
                    type: integer
                - name: y
                  description: tiles y coord
                  in: query
                  required: true
                  schema:
                    type: integer
            responses:
              200:
                description: "WGS84 extent of the tile at the given coordinates and at the given zoom level. \nQuerystring: ?zoom=<zoom level>&x=<tile x coord>&y=<tile y coord>. \nAnswer:  { minLon: <min lon>, minLat: <min lat>, maxLon: <max lon>, maxLat: <max lat> }"

      /tile_extent_merc:
          get:
            summary: Returns merc extent of the tile at the given coords.
            consumes: [application/x-www-form-urlencoded]
            produces: [application/json]
            parameters:
                - name: zoom
                  description: zoom level - from 0 to 21
                  in: query
                  required: true
                  schema:
                    type: integer
                - name: x
                  description: tiles x coord
                  in: query
                  required: true
                  schema:
                    type: integer
                - name: y
                  description: tiles y coord
                  in: query
                  required: true
                  schema:
                    type: integer
            responses:
              200:
                description: "Google Mercator extent of the tile at the given coordinates and at the given zoom level. \nQuerystring: ?zoom=<zoom level>&x=<tile x coord>&y=<tile y coord>. \nAnswer:  { minEast: <min east>, minNorth: <min north>, maxEast: <max east>, maxNorth: <max north> }"
schemes: [http]
swagger: '2.0'
host: 10.244.65.224:5000
x-21-manifest-path: /manifest
